### ISSUE TITLE
Things are broken

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphsExtras.jl#24]
I think we need to split out these packages into separate ones. BlossomV is not building properly on OSX right now, which is causing the entire package to fail. I'll be working on this shortly.

**Comment by jpfairbanks** [comment]
Blossom v is on v0.3 but LGE depends on v0.1. Could this be the source of the problem?

**Comment by sbromberger** [comment]
Perhaps. I still think we should split some of this out. It'll make it easier to troubleshoot / maintain, plus people can pick and choose. Previous discussion here: https://github.com/JuliaGraphs/LightGraphs.jl/issues/389. It looks like my concerns may have been valid.

**Comment by sbromberger** [comment]
Also, there's a HUGE security hole with Blossom right now. It's transferring over http, which makes the code modifiable (it's also failing checksums, which is really suspicious). I don't know that we want to rely on this.

**Comment by sbromberger** [comment]
OK, closing this since we've managed to split some more stuff out and get the remaining stuff working.
