### ISSUE TITLE
matching code should use standard "weights" format instead of edge dicts

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphsExtras.jl#26]
ping @mburq - would you have some time to work on this? Basically, LightGraphs has standardized on
```
distmx::AbstractMatrix = weights(g);
```
as a weights representation for weight-sensitive functions. (Basically, we pass in something that looks like an `AbstractMatrix` that defines `getindex(u, v)` and returns a weight. This allows us to do lazy evaluation of weights, and defaults, and other cool stuff.)

**Comment by mburq** [comment]
Yes that is nice. I won't have time in the next few weeks, but I can take a pass in February if it's still open. Don't hesitate to ping me again in case I forget.

**Comment by mbesancon** [comment]
cool! See https://github.com/JuliaGraphs/LightGraphsMatching.jl/issues/2 for the corresponding issue on the new LightGraphsMatching.jl

**Comment by mbesancon** [comment]
This issue can be closed here

**Comment by sbromberger** [comment]
Awesome - thanks!
