### ISSUE TITLE
Matching: Explicit solver

### ISSUE THREAD

**Issue by mbesancon** [JuliaGraphs/LightGraphsExtras.jl#27]
The build is failing, both locally for me and for [Travis](https://travis-ci.org/JuliaGraphs/LightGraphsExtras.jl/jobs/250616841), due to the call to JuMP.Model() without specifying a solver.

One LP solver should be in the REQUIRE and called by default (it can be an optional keyword argument when calling matching functions)

**Comment by sbromberger** [comment]
Mind making a PR for this?

**Comment by mbesancon** [comment]
Sure, I'm working on fixing it, I just ran into another one (see https://github.com/JuliaGraphs/LightGraphsExtras.jl/issues/28), I wanted to keep track of both to mention in the PR ;)

**Comment by sbromberger** [comment]
I just fixed #28 via #29 - take a look?
